apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: scania-test
  description: This is hellow world app
  annotations:
    github.com/project-slug: Manoj201/sc-test

spec:
  type: service
  lifecycle: experimental
  owner: guests
